spring.application.name=AxxionSystem
spring.datasource.url=jdbc:mysql://100.113.218.94:3306/sistemarenta
spring.datasource.username=root
useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.initialization-mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
spring.profiles.include=dev,mariadb
jwt.secret=b8e8812521f815c9b42345a2c526c5781d728cde9936f0f214ab013cf5fa656f
# CONFIGURACIÓN DE CORREO
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=a730419131613e
spring.mail.password=730419131613e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CONFIGURACI�N SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
