spring.application.name=AxxionSystem
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
spring.profiles.active=dev,mariadb
spring.datasource.initialization-mode=always

# CONFIGURACIÓN DE CORREO
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CONFIGURACI�N SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
