spring.application.name=AxxionSystem
spring.datasource.url=jdbc:mysql://localhost:3306/sistemarenta
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.initialization-mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.secret=55a17d9d5b586fb27f8de5bc1815ff09c98318236854d9f244b58160d5a23ffb
jwt.access-expiration=900000
jwt.refresh-expiration=604800000


# CONFIGURACIÓN DE CORREO
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=ef5d78d19e0565
spring.mail.password=b9fbfbe5eb2341
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true