#
#Wed Jul 01 12:25:01 COT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--start-maximized, --remote-allow-origins\=*, --disable-dev-shm-usage, remote-allow-origins\=*], extensions\=[]}
