#
#Fri May 22 13:28:55 COT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[remote-allow-origins\=*, --start-maximized,--disable-notifications,--disable-popup-blocking,--disable-infobars], extensions\=[]}
