#
#Mon May 04 22:04:07 GMT-05:00 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--start-maximized, --remote-allow-origins\=*, remote-allow-origins\=*], binary\=C\:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe, extensions\=[]}
